### ISSUE TITLE
Do a performance measurement of proof generation

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/merkle-drop#16]
Measure the time it takes to generate a proof based on an address file with 100.000 addresses. 
Belongs to https://github.com/trustlines-network/project/issues/350

**Comment by berndbohmeier** [comment]
We discussed that this is fine and that we will open a new issue for the small server use case with generating proofs on the fly.

**Comment by heikoheiko** [comment]
you probably figured this out yourself, but the solution is a process with a http api, which has the merkle tree in memory and can generate proofs, w/o startup time.

**Comment by berndbohmeier** [comment]
yes, we did.
